#!/usr/bin/env ruby
# frozen_string_literal: true

require "kureha"
require "optparse"

options = {}
opt_parser = OptionParser.new do |opts|
  opts.banner = "Usage: kureha [options] <ruby_file>"
  
  opts.on("-h", "--help", "Show this help message") do
    puts opts
    exit
  end
  
  opts.on("-v", "--version", "Show version") do
    puts Kureha::VERSION
    exit
  end
end

begin
  opt_parser.parse!
rescue OptionParser::InvalidOption => e
  puts e.message
  puts opt_parser
  exit 1
end

if ARGV.empty?
  puts opt_parser
  exit 1
end

file_path = ARGV[0]
unless File.exist?(file_path)
  puts "Error: File '#{file_path}' not found"
  exit 1
end

begin
  minified = Kureha::Minifier.new.minify(File.read(file_path))
  print minified  # puts の代わりに print を使用して余分な改行を避ける
rescue StandardError => e
  puts "Error: #{e.message}"
  exit 1
end 
